
--------------------
-- MouseWheel = 3 --
-- MouseB_X_1 = 4 --
-- MouseB_X_2 = 5 --
-- DPI_Cyclic = 6 --
--------------------

--GUNS--------------------------------
local AK47 = nil
local AK47_X8_SCOPE = nil
local LR300 = nil
local LR300_X8_SCOPE = nil
local MP5A4 = nil
local MP5A4_X8_SCOPE = nil
local TOMPSON = nil
local SAR = nil
local SAR_X8_SCOPE = nil
--------------------------------------

--EXTRA_PART--------------------------
function IsLeftNotPressed()
    return not IsMouseButtonPressed(1)
end
--------------------------------------

--MAIN_PART----------------------------
local gun = 0
local kickback = falseB
function OnEvent(event, arg)
--AK47
	if (event == "MOUSE_BUTTON_PRESSED" and arg == AK47) then
	kickback = not kickback
	gun = arg
	if (kickback == false) then
		OutputLogMessage("AK47_MACRO-OFF\n")
	else
		OutputLogMessage("AK47_MACRO-ON\n")
		EnablePrimaryMouseButtonEvents(true)
	end
	elseif (event == "MOUSE_BUTTON_PRESSED" and arg == AK47_X8_SCOPE) then
    kickback = not kickback
    gun = arg
    if (kickback == false) then
      	OutputLogMessage("AK47_X8_SCOPE_MACRO-OFF\n")
    else
		OutputLogMessage("AK47_X8_SCOPE_MACRO-ON\n")
		EnablePrimaryMouseButtonEvents(true)
	end
--SAR
	elseif (event == "MOUSE_BUTTON_PRESSED" and arg == SAR) then
	kickback = not kickback
	gun = arg
	if (kickback == false) then
		OutputLogMessage("SAR_MACRO-OFF\n")
		ReleaseMouseButton(1)
	else
		OutputLogMessage("SAR_MACRO-ON\n")
		EnablePrimaryMouseButtonEvents(true)
	end
	elseif (event == "MOUSE_BUTTON_PRESSED" and arg == SAR_X8_SCOPE) then
    kickback = not kickback
    gun = arg
    if (kickback == false) then
      	OutputLogMessage("SAR_X8_SCOPE_MACRO-OFF\n")
    else
		OutputLogMessage("SAR_X8_SCOPE_MACRO-ON\n")
		EnablePrimaryMouseButtonEvents(true)
	end
--LR300
	elseif (event == "MOUSE_BUTTON_PRESSED" and arg == LR300) then
    kickback = not kickback
    gun = arg
    if (kickback == false) then
      	OutputLogMessage("LR300_MACRO-OFF\n")
    else
		OutputLogMessage("LR300_MACRO-ON\n")
		EnablePrimaryMouseButtonEvents(true)
	end
	elseif (event == "MOUSE_BUTTON_PRESSED" and arg == LR300_X8_SCOPE) then
    kickback = not kickback
    gun = arg
    if (kickback == false) then
      	OutputLogMessage("LR300_X8_SCOPE_MACRO-OFF\n")
    else
		OutputLogMessage("LR300_X8_SCOPE_MACRO-ON\n")
		EnablePrimaryMouseButtonEvents(true)
	end
--MP5A4	
	elseif (event == "MOUSE_BUTTON_PRESSED" and arg == MP5A4) then
    kickback = not kickback
    gun = arg
    if (kickback == false) then
      	OutputLogMessage("MP5A4_MACRO-OFF\n")
    else
		OutputLogMessage("MP5A4_MACRO-ON\n")
		EnablePrimaryMouseButtonEvents(true)
	end
	elseif (event == "MOUSE_BUTTON_PRESSED" and arg == MP5A4_X8_SCOPE) then
    kickback = not kickback
    gun = arg
    if (kickback == false) then
      	OutputLogMessage("MP5A4_X8_SCOPE_MACRO-OFF\n")
    else
		OutputLogMessage("MP5A4_X8_SCOPE_MACRO-ON\n")
		EnablePrimaryMouseButtonEvents(true)
	end
--TOMPSON
	elseif (event == "MOUSE_BUTTON_PRESSED" and arg == TOMPSON) then
    kickback = not kickback
    gun = arg
    if (kickback == false) then
      	OutputLogMessage("TOMPSON_MACRO-OFF\n")
    else
		OutputLogMessage("TOMPSON_MACRO-ON\n")
		EnablePrimaryMouseButtonEvents(true)
	end	
	end
---------------------------------------

--Recoil_Tables------------------------
if gun == SAR then
		if kickback then
		repeat
			if IsMouseButtonPressed(1) then
			if IsMouseButtonPressed(3) then
			PressMouseButton(1)
			Sleep(50)
			ReleaseMouseButton(1)
			Sleep(10)
			MoveMouseRelative(math.random(-0.8, 0.4), 4)
			Sleep(16)
			MoveMouseRelative(math.random(-0.8, 0.4), 4)
			Sleep(18)
			MoveMouseRelative(math.random(-0.8, 0.4), 4)
			Sleep(16)
			MoveMouseRelative(math.random(-0.7, 0.4), 4)
			Sleep(18)
			MoveMouseRelative(math.random(-0.11, 0.5), 3.5)
			Sleep(16)
			MoveMouseRelative(math.random(-0.11, 0.6), 3)
			Sleep(18)
			MoveMouseRelative(math.random(-0.8, 0.4), 2)
			Sleep(20)
			PressMouseButton(1)
			end
			end
        until not IsMouseButtonPressed(3)
			if not IsMouseButtonPressed(3) then 
				ReleaseMouseButton(1)
			end
    end	
	
	elseif gun == SAR_X8_SCOPE then
		if kickback then
		repeat
			if IsMouseButtonPressed(1) then
			if IsMouseButtonPressed(3) then
			PressMouseButton(1)
            Sleep(50)
            ReleaseMouseButton(1)
            Sleep(10)
            MoveMouseRelative(math.random(-2, 2), 16)
            Sleep(16)
            MoveMouseRelative(math.random(-2, 2.1), 16)
            Sleep(18)
            MoveMouseRelative(math.random(-2, 2), 14)
            Sleep(16)
            MoveMouseRelative(math.random(-2, 2.1), 13.5)
            Sleep(18)
            MoveMouseRelative(math.random(-2, 2.1), 13)
            Sleep(16)
            MoveMouseRelative(math.random(-2, 2.1), 13)
            Sleep(18)
            MoveMouseRelative(math.random(-2, 2), 9.3)
            Sleep(20)
            PressMouseButton(1)
			end
			end
        until not IsMouseButtonPressed(3)
			if not IsMouseButtonPressed(3) then 
				ReleaseMouseButton(1)
			end
    end

    elseif gun == AK47 then
		if kickback then
		repeat
		if (IsLeftNotPressed()) then return end
			Sleep(2)
			MoveMouseRelative(-3, 4)
			Sleep(16)
			MoveMouseRelative(-3, 4)
			Sleep(17)
			MoveMouseRelative(-3, 4)
			Sleep(17)
			MoveMouseRelative(-3, 4)
			Sleep(17)
			MoveMouseRelative(-3, 4)
			Sleep(17)
			MoveMouseRelative(-3, 5)
			Sleep(17)
			MoveMouseRelative(-3, 5)
		if (IsLeftNotPressed()) then return end
			Sleep(39)
			MoveMouseRelative(1, 5)
			Sleep(17)
			MoveMouseRelative(1, 5)
			Sleep(17)
			MoveMouseRelative(1, 5)
			Sleep(17)
			MoveMouseRelative(1, 5)
			Sleep(17)
			MoveMouseRelative(0, 6)
		if (IsLeftNotPressed()) then return end
			Sleep(56)
			MoveMouseRelative(-4, 3)
			Sleep(15)
			MoveMouseRelative(-4, 3)
			Sleep(15)
			MoveMouseRelative(-4, 3)
			Sleep(15)
			MoveMouseRelative(-4, 3)
			Sleep(15)
			MoveMouseRelative(-4, 3)
			Sleep(15)
			MoveMouseRelative(-4, 3)
			Sleep(15)
			MoveMouseRelative(-5, 3)
			Sleep(15)
			MoveMouseRelative(-5, 3)
		if (IsLeftNotPressed()) then return end
			Sleep(25)
			MoveMouseRelative(-3, 3)
			Sleep(15)
			MoveMouseRelative(-3, 3)
			Sleep(15)
			MoveMouseRelative(-3, 3)
			Sleep(15)
			MoveMouseRelative(-3, 3)
			Sleep(15)
			MoveMouseRelative(-4, 3)
			Sleep(15)
			MoveMouseRelative(-4, 3)
			Sleep(15)
			MoveMouseRelative(-4, 3)
		if (IsLeftNotPressed()) then return end
			Sleep(33)
			MoveMouseRelative(0, 5)
			Sleep(15)
			MoveMouseRelative(0, 5)
			Sleep(15)
			MoveMouseRelative(0, 5)
			Sleep(15)
			MoveMouseRelative(0, 6)
		if (IsLeftNotPressed()) then return end
			Sleep(88)
			MoveMouseRelative(2, 4)
			Sleep(15)
			MoveMouseRelative(2, 4)
			Sleep(15)
			MoveMouseRelative(3, 5)
			Sleep(15)
			MoveMouseRelative(3, 5)
		if (IsLeftNotPressed()) then return end
			Sleep(81)
			MoveMouseRelative(4, 3)
			Sleep(17)
			MoveMouseRelative(4, 3)
			Sleep(17)
			MoveMouseRelative(4, 4)
			Sleep(17)
			MoveMouseRelative(5, 4)
		if (IsLeftNotPressed()) then return end
			Sleep(72)
			MoveMouseRelative(4, 2)
			Sleep(16)
			MoveMouseRelative(4, 2)
			Sleep(16)
			MoveMouseRelative(5, 2)
			Sleep(16)
			MoveMouseRelative(5, 3)
			Sleep(16)
			MoveMouseRelative(5, 3)
		if (IsLeftNotPressed()) then return end
			Sleep(71)
			MoveMouseRelative(5, 1)
			Sleep(16)
			MoveMouseRelative(5, 2)
			Sleep(16)
			MoveMouseRelative(5, 2)
			Sleep(16)
			MoveMouseRelative(5, 2)
			Sleep(16)
			MoveMouseRelative(5, 2)
		if (IsLeftNotPressed()) then return end
			Sleep(60)
			MoveMouseRelative(5, 1)
			Sleep(17)
			MoveMouseRelative(5, 1)
			Sleep(17)
			MoveMouseRelative(5, 1)
			Sleep(17)
			MoveMouseRelative(5, 1)
			Sleep(17)
			MoveMouseRelative(5, 2)
		if (IsLeftNotPressed()) then return end
			Sleep(63)
			MoveMouseRelative(5, 1)
			Sleep(17)
			MoveMouseRelative(5, 1)
			Sleep(17)
			MoveMouseRelative(6, 2)
			Sleep(17)
			MoveMouseRelative(6, 2)
		if (IsLeftNotPressed()) then return end
			Sleep(85)
			MoveMouseRelative(4, 2)
			Sleep(17)
			MoveMouseRelative(4, 3)
			Sleep(18)
			MoveMouseRelative(5, 3)
			Sleep(17)
			MoveMouseRelative(5, 3)
		if (IsLeftNotPressed()) then return end
			Sleep(74)
			MoveMouseRelative(3, 4)
			Sleep(17)
			MoveMouseRelative(3, 5)
			Sleep(17)
			MoveMouseRelative(4, 5)
		if (IsLeftNotPressed()) then return end
			Sleep(102)
			MoveMouseRelative(0, 5)
			Sleep(17)
			MoveMouseRelative(0, 6)
			Sleep(17)
			MoveMouseRelative(0, 6)
		if (IsLeftNotPressed()) then return end
			Sleep(92)
			MoveMouseRelative(-2, 4)
			Sleep(17)
			MoveMouseRelative(-2, 5)
			Sleep(17)
			MoveMouseRelative(-2, 5)
			Sleep(17)
			MoveMouseRelative(-3, 5)
		if (IsLeftNotPressed()) then return end
			Sleep(74)
			MoveMouseRelative(-3, 4)
			Sleep(17)
			MoveMouseRelative(-3, 4)
			Sleep(17)
			MoveMouseRelative(-3, 4)
			Sleep(17)
			MoveMouseRelative(-4, 4)
			Sleep(17)
			MoveMouseRelative(-4, 4)
		if (IsLeftNotPressed()) then return end
			Sleep(66)
			MoveMouseRelative(-4, 4)
			Sleep(17)
			MoveMouseRelative(-4, 4)
			Sleep(17)
			MoveMouseRelative(-4, 4)
			Sleep(17)
			MoveMouseRelative(-5, 4)
			Sleep(17)
			MoveMouseRelative(-5, 4)
		if (IsLeftNotPressed()) then return end
			Sleep(55)
			MoveMouseRelative(-4, 2)
			Sleep(17)
			MoveMouseRelative(-4, 2)
			Sleep(17)
			MoveMouseRelative(-4, 3)
			Sleep(17)
			MoveMouseRelative(-4, 3)
			Sleep(17)
			MoveMouseRelative(-4, 3)
			Sleep(17)
			MoveMouseRelative(-5, 3)
		if (IsLeftNotPressed()) then return end
			Sleep(49)
			MoveMouseRelative(-4, 2)
			Sleep(17)
			MoveMouseRelative(-4, 2)
			Sleep(17)
			MoveMouseRelative(-5, 2)
			Sleep(17)
			MoveMouseRelative(-5, 3)
			Sleep(17)
			MoveMouseRelative(-5, 3)
			Sleep(17)
			MoveMouseRelative(-5, 3)
		if (IsLeftNotPressed()) then return end
			Sleep(27)
			MoveMouseRelative(-5, 2)
			Sleep(17)
			MoveMouseRelative(-5, 2)
			Sleep(17)
			MoveMouseRelative(-5, 2)
			Sleep(17)
			MoveMouseRelative(-5, 2)
			Sleep(17)
			MoveMouseRelative(-5, 2)
		if (IsLeftNotPressed()) then return end
			Sleep(74)
			MoveMouseRelative(-5, 1)
			Sleep(17)
			MoveMouseRelative(-5, 1)
			Sleep(17)
			MoveMouseRelative(-5, 1)
			Sleep(17)
			MoveMouseRelative(-6, 1)
			Sleep(17)
			MoveMouseRelative(-6, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(57)
			MoveMouseRelative(-5, 1)
			Sleep(17)
			MoveMouseRelative(-5, 1)
			Sleep(17)
			MoveMouseRelative(-5, 1)
			Sleep(17)
			MoveMouseRelative(-5, 1)
			Sleep(17)
			MoveMouseRelative(0, 0)
        until (IsLeftNotPressed())
    end

elseif gun == AK47_X8_SCOPE then
	if kickback then
		repeat
		if (IsLeftNotPressed()) then return end
			Sleep(2)
			MoveMouseRelative(-12, 15)
			Sleep(16)
			MoveMouseRelative(-12, 15)
			Sleep(17)
			MoveMouseRelative(-12, 15)
			Sleep(17)
			MoveMouseRelative(-12, 15)
			Sleep(17)
			MoveMouseRelative(-12, 15)
			Sleep(17)
			MoveMouseRelative(-12, 19)
			Sleep(17)
			MoveMouseRelative(-12, 19)
		if (IsLeftNotPressed()) then return end
			Sleep(39)
			MoveMouseRelative(4, 19)
			Sleep(17)
			MoveMouseRelative(4, 19)
			Sleep(17)
			MoveMouseRelative(4, 19)
			Sleep(17)
			MoveMouseRelative(4, 19)
			Sleep(17)
			MoveMouseRelative(0, 23)
		if (IsLeftNotPressed()) then return end
			Sleep(56)
			MoveMouseRelative(-16, 12)
			Sleep(15)
			MoveMouseRelative(-16, 12)
			Sleep(15)
			MoveMouseRelative(-16, 12)
			Sleep(15)
			MoveMouseRelative(-16, 12)
			Sleep(15)
			MoveMouseRelative(-16, 12)
			Sleep(15)
			MoveMouseRelative(-16, 12)
			Sleep(15)
			MoveMouseRelative(-20, 12)
			Sleep(15)
			MoveMouseRelative(-20, 12)
		if (IsLeftNotPressed()) then return end
			Sleep(25)
			MoveMouseRelative(-12, 12)
			Sleep(15)
			MoveMouseRelative(-12, 12)
			Sleep(15)
			MoveMouseRelative(-12, 12)
			Sleep(15)
			MoveMouseRelative(-12, 12)
			Sleep(15)
			MoveMouseRelative(-16, 12)
			Sleep(15)
			MoveMouseRelative(-16, 12)
			Sleep(15)
			MoveMouseRelative(-16, 12)
		if (IsLeftNotPressed()) then return end
			Sleep(33)
			MoveMouseRelative(0, 19)
			Sleep(15)
			MoveMouseRelative(0, 19)
			Sleep(15)
			MoveMouseRelative(0, 19)
			Sleep(15)
			MoveMouseRelative(0, 23)
		if (IsLeftNotPressed()) then return end
			Sleep(88)
			MoveMouseRelative(8, 15)
			Sleep(15)
			MoveMouseRelative(8, 15)
			Sleep(15)
			MoveMouseRelative(12, 19)
			Sleep(15)
			MoveMouseRelative(12, 19)
		if (IsLeftNotPressed()) then return end
			Sleep(81)
			MoveMouseRelative(15, 12)
			Sleep(17)
			MoveMouseRelative(15, 12)
			Sleep(17)
			MoveMouseRelative(15, 15)
			Sleep(17)
			MoveMouseRelative(19, 15)
		if (IsLeftNotPressed()) then return end
			Sleep(72)
			MoveMouseRelative(15, 8)
			Sleep(16)
			MoveMouseRelative(15, 8)
			Sleep(16)
			MoveMouseRelative(19, 8)
			Sleep(16)
			MoveMouseRelative(19, 12)
			Sleep(16)
			MoveMouseRelative(19, 12)
		if (IsLeftNotPressed()) then return end
			Sleep(71)
			MoveMouseRelative(19, 4)
			Sleep(16)
			MoveMouseRelative(19, 8)
			Sleep(16)
			MoveMouseRelative(19, 8)
			Sleep(16)
			MoveMouseRelative(19, 8)
			Sleep(16)
			MoveMouseRelative(19, 8)
		if (IsLeftNotPressed()) then return end
			Sleep(60)
			MoveMouseRelative(19, 4)
			Sleep(17)
			MoveMouseRelative(19, 4)
			Sleep(17)
			MoveMouseRelative(19, 4)
			Sleep(17)
			MoveMouseRelative(19, 4)
			Sleep(17)
			MoveMouseRelative(19, 8)
		if (IsLeftNotPressed()) then return end
			Sleep(63)
			MoveMouseRelative(20, 4)
			Sleep(17)
			MoveMouseRelative(20, 4)
			Sleep(17)
			MoveMouseRelative(24, 8)
			Sleep(17)
			MoveMouseRelative(24, 8)
		if (IsLeftNotPressed()) then return end
			Sleep(85)
			MoveMouseRelative(16, 8)
			Sleep(17)
			MoveMouseRelative(16, 12)
			Sleep(18)
			MoveMouseRelative(20, 12)
			Sleep(17)
			MoveMouseRelative(20, 12)
		if (IsLeftNotPressed()) then return end
			Sleep(74)
			MoveMouseRelative(13, 15)
			Sleep(17)
			MoveMouseRelative(13, 19)
			Sleep(17)
			MoveMouseRelative(16, 19)
		if (IsLeftNotPressed()) then return end
			Sleep(102)
			MoveMouseRelative(1, 19)
			Sleep(17)
			MoveMouseRelative(1, 23)
			Sleep(17)
			MoveMouseRelative(1, 23)
		if (IsLeftNotPressed()) then return end
			Sleep(92)
			MoveMouseRelative(-7, 15)
			Sleep(17)
			MoveMouseRelative(-7, 19)
			Sleep(17)
			MoveMouseRelative(-7, 19)
			Sleep(17)
			MoveMouseRelative(-11, 19)
		if (IsLeftNotPressed()) then return end
			Sleep(74)
			MoveMouseRelative(-11, 15)
			Sleep(17)
			MoveMouseRelative(-11, 15)
			Sleep(17)
			MoveMouseRelative(-11, 15)
			Sleep(17)
			MoveMouseRelative(-15, 15)
			Sleep(17)
			MoveMouseRelative(-15, 15)
		if (IsLeftNotPressed()) then return end
			Sleep(66)
			MoveMouseRelative(-15, 15)
			Sleep(17)
			MoveMouseRelative(-15, 15)
			Sleep(17)
			MoveMouseRelative(-15, 15)
			Sleep(17)
			MoveMouseRelative(-19, 15)
			Sleep(17)
			MoveMouseRelative(-19, 15)
		if (IsLeftNotPressed()) then return end
			Sleep(55)
			MoveMouseRelative(-16, 8)
			Sleep(17)
			MoveMouseRelative(-16, 8)
			Sleep(17)
			MoveMouseRelative(-16, 12)
			Sleep(17)
			MoveMouseRelative(-16, 12)
			Sleep(17)
			MoveMouseRelative(-16, 12)
			Sleep(17)
			MoveMouseRelative(-20, 12)
		if (IsLeftNotPressed()) then return end
			Sleep(49)
			MoveMouseRelative(-16, 8)
			Sleep(17)
			MoveMouseRelative(-16, 8)
			Sleep(17)
			MoveMouseRelative(-20, 8)
			Sleep(17)
			MoveMouseRelative(-20, 12)
			Sleep(17)
			MoveMouseRelative(-20, 12)
			Sleep(17)
			MoveMouseRelative(-20, 12)
		if (IsLeftNotPressed()) then return end
			Sleep(27)
			MoveMouseRelative(-20, 8)
			Sleep(17)
			MoveMouseRelative(-20, 8)
			Sleep(17)
			MoveMouseRelative(-20, 8)
			Sleep(17)
			MoveMouseRelative(-20, 8)
			Sleep(17)
			MoveMouseRelative(-20, 8)
		if (IsLeftNotPressed()) then return end
			Sleep(74)
			MoveMouseRelative(-20, 4)
			Sleep(17)
			MoveMouseRelative(-20, 4)
			Sleep(17)
			MoveMouseRelative(-20, 4)
			Sleep(17)
			MoveMouseRelative(-23, 4)
			Sleep(17)
			MoveMouseRelative(-23, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(57)
			MoveMouseRelative(-20, 4)
			Sleep(17)
			MoveMouseRelative(-20, 4)
			Sleep(17)
			MoveMouseRelative(-20, 4)
			Sleep(17)
			MoveMouseRelative(-20, 4)
			Sleep(17)
			MoveMouseRelative(0, 0)
		until (IsLeftNotPressed())
	end

	elseif gun == LR300 then
		if kickback then
		repeat
		if (IsLeftNotPressed()) then return end
			MoveMouseRelative(-1, 2)
            Sleep(7)
            MoveMouseRelative(0, 2)
            Sleep(7)
            MoveMouseRelative(0, 2)
            Sleep(7)
            MoveMouseRelative(0, 2)
            Sleep(7)
            MoveMouseRelative(0, 2)
            Sleep(7)
            MoveMouseRelative(0, 2)
            Sleep(7)
            MoveMouseRelative(0, 2)
            Sleep(8)
            MoveMouseRelative(0, 1)
		if (IsLeftNotPressed()) then return end
			Sleep(72)
			MoveMouseRelative(-1, 2)
			Sleep(7)
			MoveMouseRelative(-1, 2)
			Sleep(7)
			MoveMouseRelative(-1, 2)
			Sleep(7)
			MoveMouseRelative(-1, 2)
			Sleep(7)
			MoveMouseRelative(0, 2)
			Sleep(8)
			MoveMouseRelative(0, 2)
			Sleep(7)
			MoveMouseRelative(0, 2)
			Sleep(6)
			MoveMouseRelative(0, 2)
			Sleep(7)
			MoveMouseRelative(0, 2)
		if (IsLeftNotPressed()) then return end
			Sleep(55)
			MoveMouseRelative(-1, 2)
			Sleep(7)
			MoveMouseRelative(-1, 2)
			Sleep(8)
			MoveMouseRelative(-1, 2)
			Sleep(7)
			MoveMouseRelative(-1, 2)
			Sleep(7)
			MoveMouseRelative(-1, 2)
			Sleep(7)
			MoveMouseRelative(-1, 2)
			Sleep(7)
			MoveMouseRelative(0, 2)
			Sleep(7)
			MoveMouseRelative(0, 2)
			Sleep(7)
			MoveMouseRelative(0, 2)
			Sleep(7)
			MoveMouseRelative(0, 1)
			Sleep(7)
			MoveMouseRelative(0, 1)
		if (IsLeftNotPressed()) then return end
			Sleep(42)
			MoveMouseRelative(-1, 2)
			Sleep(6)
			MoveMouseRelative(-1, 2)
			Sleep(7)
			MoveMouseRelative(-1, 2)
			Sleep(7)
			MoveMouseRelative(-1, 2)
			Sleep(7)
			MoveMouseRelative(-1, 2)
			Sleep(8)
			MoveMouseRelative(-1, 2)
			Sleep(6)
			MoveMouseRelative(-1, 2)
			Sleep(8)
			MoveMouseRelative(-1, 1)
			Sleep(6)
			MoveMouseRelative(-1, 1)
			Sleep(7)
			MoveMouseRelative(0, 1)
			Sleep(7)
			MoveMouseRelative(0, 1)
		if (IsLeftNotPressed()) then return end
			Sleep(50)
			MoveMouseRelative(-1, 2)
			Sleep(7)
			MoveMouseRelative(-1, 2)
			Sleep(7)
			MoveMouseRelative(-1, 2)
			Sleep(7)
			MoveMouseRelative(-1, 2)
			Sleep(7)
			MoveMouseRelative(-1, 2)
			Sleep(6)
			MoveMouseRelative(-1, 2)
			Sleep(8)
			MoveMouseRelative(-1, 1)
			Sleep(7)
			MoveMouseRelative(-1, 1)
			Sleep(7)
			MoveMouseRelative(-1, 1)
		if (IsLeftNotPressed()) then return end
			Sleep(39)
			MoveMouseRelative(-2, 2)
			Sleep(7)
			MoveMouseRelative(-2, 2)
			Sleep(7)
			MoveMouseRelative(-1, 2)
			Sleep(8)
			MoveMouseRelative(-1, 2)
			Sleep(6)
			MoveMouseRelative(-1, 2)
			Sleep(7)
			MoveMouseRelative(-1, 2)
			Sleep(7)
			MoveMouseRelative(-1, 1)
		if (IsLeftNotPressed()) then return end
			Sleep(76)
			MoveMouseRelative(-1, 2)
			Sleep(6)
			MoveMouseRelative(-1, 2)
			Sleep(7)
			MoveMouseRelative(-1, 2)
			Sleep(7)
			MoveMouseRelative(-1, 2)
			Sleep(7)
			MoveMouseRelative(-1, 1)
			Sleep(7)
			MoveMouseRelative(0, 1)
		if (IsLeftNotPressed()) then return end
			Sleep(77)
			MoveMouseRelative(-1, 3)
			Sleep(7)
			MoveMouseRelative(-1, 3)
			Sleep(8)
			MoveMouseRelative(0, 2)
			Sleep(6)
			MoveMouseRelative(0, 2)
		if (IsLeftNotPressed()) then return end
			Sleep(98)
			MoveMouseRelative(2, 2)
			Sleep(7)
			MoveMouseRelative(2, 2)
			Sleep(7)
			MoveMouseRelative(1, 2)
			Sleep(7)
			MoveMouseRelative(1, 1)
		if (IsLeftNotPressed()) then return end
			Sleep(98)
			MoveMouseRelative(2, 1)
			Sleep(7)
			MoveMouseRelative(2, 1)
			Sleep(7)
			MoveMouseRelative(2, 1)
			Sleep(6)
			MoveMouseRelative(2, 1)
			Sleep(8)
			MoveMouseRelative(1, 1)
			Sleep(6)
			MoveMouseRelative(1, 1)
		if (IsLeftNotPressed()) then return end
			Sleep(77)
			MoveMouseRelative(2, 1)
			Sleep(7)
			MoveMouseRelative(2, 1)
			Sleep(7)
			MoveMouseRelative(2, 1)
			Sleep(7)
			MoveMouseRelative(2, 1)
			Sleep(7)
			MoveMouseRelative(2, 1)
			Sleep(8)
			MoveMouseRelative(2, 1)
			Sleep(6)
			MoveMouseRelative(1, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(70)
			MoveMouseRelative(2, 1)
			Sleep(8)
			MoveMouseRelative(2, 1)
			Sleep(7)
			MoveMouseRelative(2, 1)
			Sleep(6)
			MoveMouseRelative(2, 1)
			Sleep(8)
			MoveMouseRelative(1, 0)
			Sleep(7)
			MoveMouseRelative(1, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(77)
			MoveMouseRelative(2, 1)
			Sleep(7)
			MoveMouseRelative(2, 1)
			Sleep(7)
			MoveMouseRelative(1, 1)
			Sleep(7)
			MoveMouseRelative(1, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(96)
			MoveMouseRelative(-1, 2)
			Sleep(7)
			MoveMouseRelative(0, 1)
		if (IsLeftNotPressed()) then return end
			Sleep(111)
			MoveMouseRelative(-1, 1)
			Sleep(7)
			MoveMouseRelative(-1, 1)
			Sleep(7)
			MoveMouseRelative(-1, 1)
		if (IsLeftNotPressed()) then return end
			Sleep(90)
			MoveMouseRelative(-2, 1)
			Sleep(7)
			MoveMouseRelative(-1, 1)
			Sleep(7)
			MoveMouseRelative(-1, 0)
			Sleep(7)
			MoveMouseRelative(-1, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(97)
			MoveMouseRelative(-2, 1)
			Sleep(7)
			MoveMouseRelative(-2, 1)
			Sleep(7)
			MoveMouseRelative(-2, 0)
			Sleep(8)
			MoveMouseRelative(-2, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(90)
			MoveMouseRelative(-2, 1)
			Sleep(7)
			MoveMouseRelative(-2, 1)
			Sleep(7)
			MoveMouseRelative(-2, 0)
			Sleep(7)
			MoveMouseRelative(-1, 0)
			Sleep(7)
			MoveMouseRelative(-1, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(92)
			MoveMouseRelative(-2, 1)
			Sleep(6)
			MoveMouseRelative(-2, 0)
			Sleep(7)
			MoveMouseRelative(-2, 0)
			Sleep(7)
			MoveMouseRelative(-2, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(92)
			MoveMouseRelative(-2, 1)
			Sleep(7)
			MoveMouseRelative(-2, 1)
			Sleep(6)
			MoveMouseRelative(-2, 0)
			Sleep(8)
			MoveMouseRelative(-2, 0)
			Sleep(6)
			MoveMouseRelative(-1, 0)
			Sleep(8)
			MoveMouseRelative(-1, 0)
			MoveMouseRelative(0, 0)
		until (IsLeftNotPressed())
	end

	elseif gun == LR300_X8_SCOPE then
		if kickback then
		repeat
		if (IsLeftNotPressed()) then return end
			MoveMouseRelative(-4, 8)
			Sleep(7)
			MoveMouseRelative(0, 8)
			Sleep(7)
			MoveMouseRelative(0, 8)
			Sleep(7)
			MoveMouseRelative(0, 8)
			Sleep(7)
			MoveMouseRelative(0, 8)
			Sleep(7)
			MoveMouseRelative(0, 8)
			Sleep(7)
			MoveMouseRelative(0, 8)
			Sleep(8)
			MoveMouseRelative(0, 4)
		if (IsLeftNotPressed()) then return end
			Sleep(72)
			MoveMouseRelative(-4, 8)
			Sleep(7)
			MoveMouseRelative(-4, 8)
			Sleep(7)
			MoveMouseRelative(-4, 8)
			Sleep(7)
			MoveMouseRelative(-4, 8)
			Sleep(7)
			MoveMouseRelative(0, 8)
			Sleep(8)
			MoveMouseRelative(0, 8)
			Sleep(7)
			MoveMouseRelative(0, 8)
			Sleep(6)
			MoveMouseRelative(0, 8)
			Sleep(7)
			MoveMouseRelative(0, 8)
		if (IsLeftNotPressed()) then return end
			Sleep(55)
			MoveMouseRelative(-4, 8)
			Sleep(7)
			MoveMouseRelative(-4, 8)
			Sleep(8)
			MoveMouseRelative(-4, 8)
			Sleep(7)
			MoveMouseRelative(-4, 8)
			Sleep(7)
			MoveMouseRelative(-4, 8)
			Sleep(7)
			MoveMouseRelative(-4, 8)
			Sleep(7)
			MoveMouseRelative(0, 8)
			Sleep(7)
			MoveMouseRelative(0, 8)
			Sleep(7)
			MoveMouseRelative(0, 8)
			Sleep(7)
			MoveMouseRelative(0, 4)
			Sleep(7)
			MoveMouseRelative(0, 4)
		if (IsLeftNotPressed()) then return end
			Sleep(42)
			MoveMouseRelative(-4, 8)
			Sleep(6)
			MoveMouseRelative(-4, 8)
			Sleep(7)
			MoveMouseRelative(-4, 8)
			Sleep(7)
			MoveMouseRelative(-4, 8)
			Sleep(7)
			MoveMouseRelative(-4, 8)
			Sleep(8)
			MoveMouseRelative(-4, 8)
			Sleep(6)
			MoveMouseRelative(-4, 8)
			Sleep(8)
			MoveMouseRelative(-4, 4)
			Sleep(6)
			MoveMouseRelative(-4, 4)
			Sleep(7)
			MoveMouseRelative(0, 4)
			Sleep(7)
			MoveMouseRelative(0, 4)
		if (IsLeftNotPressed()) then return end
			Sleep(50)
			MoveMouseRelative(-4, 8)
			Sleep(7)
			MoveMouseRelative(-4, 8)
			Sleep(7)
			MoveMouseRelative(-4, 8)
			Sleep(7)
			MoveMouseRelative(-4, 8)
			Sleep(7)
			MoveMouseRelative(-4, 8)
			Sleep(6)
			MoveMouseRelative(-4, 8)
			Sleep(8)
			MoveMouseRelative(-4, 4)
			Sleep(7)
			MoveMouseRelative(-4, 4)
			Sleep(7)
			MoveMouseRelative(-4, 4)
		if (IsLeftNotPressed()) then return end
			Sleep(39)
			MoveMouseRelative(-8, 8)
			Sleep(7)
			MoveMouseRelative(-8, 8)
			Sleep(7)
			MoveMouseRelative(-4, 8)
			Sleep(8)
			MoveMouseRelative(-4, 8)
			Sleep(6)
			MoveMouseRelative(-4, 8)
			Sleep(7)
			MoveMouseRelative(-4, 8)
			Sleep(7)
			MoveMouseRelative(-4, 4)
		if (IsLeftNotPressed()) then return end
			Sleep(76)
			MoveMouseRelative(-4, 8)
			Sleep(6)
			MoveMouseRelative(-4, 8)
			Sleep(7)
			MoveMouseRelative(-4, 8)
			Sleep(7)
			MoveMouseRelative(-4, 8)
			Sleep(7)
			MoveMouseRelative(-4, 4)
			Sleep(7)
			MoveMouseRelative(0, 4)
		if (IsLeftNotPressed()) then return end
			Sleep(77)
			MoveMouseRelative(-4, 11)
			Sleep(7)
			MoveMouseRelative(-4, 11)
			Sleep(8)
			MoveMouseRelative(0, 8)
			Sleep(6)
			MoveMouseRelative(0, 8)
		if (IsLeftNotPressed()) then return end
			Sleep(98)
			MoveMouseRelative(8, 8)
			Sleep(7)
			MoveMouseRelative(8, 8)
			Sleep(7)
			MoveMouseRelative(4, 8)
			Sleep(7)
			MoveMouseRelative(4, 4)
		if (IsLeftNotPressed()) then return end
			Sleep(98)
			MoveMouseRelative(8, 4)
			Sleep(7)
			MoveMouseRelative(8, 4)
			Sleep(7)
			MoveMouseRelative(8, 4)
			Sleep(6)
			MoveMouseRelative(8, 4)
			Sleep(8)
			MoveMouseRelative(4, 4)
			Sleep(6)
			MoveMouseRelative(4, 4)
		if (IsLeftNotPressed()) then return end
			Sleep(77)
			MoveMouseRelative(8, 4)
			Sleep(7)
			MoveMouseRelative(8, 4)
			Sleep(7)
			MoveMouseRelative(8, 4)
			Sleep(7)
			MoveMouseRelative(8, 4)
			Sleep(7)
			MoveMouseRelative(8, 4)
			Sleep(8)
			MoveMouseRelative(8, 4)
			Sleep(6)
			MoveMouseRelative(4, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(70)
			MoveMouseRelative(8, 4)
			Sleep(8)
			MoveMouseRelative(8, 4)
			Sleep(7)
			MoveMouseRelative(8, 4)
			Sleep(6)
			MoveMouseRelative(8, 4)
			Sleep(8)
			MoveMouseRelative(4, 0)
			Sleep(7)
			MoveMouseRelative(4, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(77)
			MoveMouseRelative(8, 4)
			Sleep(7)
			MoveMouseRelative(8, 4)
			Sleep(7)
			MoveMouseRelative(4, 4)
			Sleep(7)
			MoveMouseRelative(4, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(96)
			MoveMouseRelative(-4, 8)
			Sleep(7)
			MoveMouseRelative(0, 4)
		if (IsLeftNotPressed()) then return end
			Sleep(111)
			MoveMouseRelative(-4, 4)
			Sleep(7)
			MoveMouseRelative(-4, 4)
			Sleep(7)
			MoveMouseRelative(-4, 4)
			Sleep(90)
			MoveMouseRelative(-8, 4)
			Sleep(7)
			MoveMouseRelative(-4, 4)
			Sleep(7)
			MoveMouseRelative(-4, 0)
			Sleep(7)
			MoveMouseRelative(-4, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(97)
			MoveMouseRelative(-8, 4)
			Sleep(7)
			MoveMouseRelative(-8, 4)
			Sleep(7)
			MoveMouseRelative(-8, 0)
			Sleep(8)
			MoveMouseRelative(-8, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(90)
			MoveMouseRelative(-8, 4)
			Sleep(7)
			MoveMouseRelative(-8, 4)
			Sleep(7)
			MoveMouseRelative(-8, 0)
			Sleep(7)
			MoveMouseRelative(-4, 0)
			Sleep(7)
			MoveMouseRelative(-4, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(92)
			MoveMouseRelative(-8, 4)
			Sleep(6)
			MoveMouseRelative(-8, 0)
			Sleep(7)
			MoveMouseRelative(-8, 0)
			Sleep(7)
			MoveMouseRelative(-8, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(92)
			MoveMouseRelative(-8, 4)
			Sleep(7)
			MoveMouseRelative(-8, 4)
			Sleep(6)
			MoveMouseRelative(-8, 0)
			Sleep(8)
			MoveMouseRelative(-8, 0)
			Sleep(6)
			MoveMouseRelative(-4, 0)
			Sleep(8)
			MoveMouseRelative(-4, 0)
			MoveMouseRelative(0, 0)
		until (IsLeftNotPressed())
	end
	
	elseif gun == MP5A4 then
		if kickback then
		repeat
		if (IsLeftNotPressed()) then return end
            MoveMouseRelative(0, 3)
			Sleep(12)
			MoveMouseRelative(0, 3)
			Sleep(13)
			MoveMouseRelative(0, 3)
			Sleep(13)
			MoveMouseRelative(0, 4)
		if (IsLeftNotPressed()) then return end
			Sleep(75)
			MoveMouseRelative(0, 4)
			Sleep(15)
			MoveMouseRelative(0, 4)
			Sleep(15)
			MoveMouseRelative(0, 4)
			Sleep(15)
			MoveMouseRelative(0, 5)
		if (IsLeftNotPressed()) then return end
			Sleep(55)
			MoveMouseRelative(0, 5)
			Sleep(18)
			MoveMouseRelative(0, 5)
			Sleep(18)
			MoveMouseRelative(0, 5)
			Sleep(18)
			MoveMouseRelative(0, 5)
		if (IsLeftNotPressed()) then return end
			Sleep(38)
			MoveMouseRelative(1, 5)
			Sleep(18)
			MoveMouseRelative(2, 5)
			Sleep(18)
			MoveMouseRelative(2, 5)
			Sleep(18)
			MoveMouseRelative(2, 5)
		if (IsLeftNotPressed()) then return end
			Sleep(47)
			MoveMouseRelative(4, 4)
			Sleep(23)
			MoveMouseRelative(4, 4)
			Sleep(23)
			MoveMouseRelative(5, 4)
			Sleep(23)
			MoveMouseRelative(5, 5)
		if (IsLeftNotPressed()) then return end
			Sleep(28)
			MoveMouseRelative(5, 3)
			Sleep(20)
			MoveMouseRelative(5, 3)
			Sleep(20)
			MoveMouseRelative(5, 4)
			Sleep(20)
			MoveMouseRelative(5, 4)
		if (IsLeftNotPressed()) then return end
			Sleep(37)
			MoveMouseRelative(3, 2)
			Sleep(16)
			MoveMouseRelative(3, 2)
			Sleep(16)
			MoveMouseRelative(3, 2)
			Sleep(16)
			MoveMouseRelative(4, 2)
		if (IsLeftNotPressed()) then return end
			Sleep(45)
			MoveMouseRelative(0, 1)
			Sleep(5)
			MoveMouseRelative(0, 1)
			Sleep(5)
			MoveMouseRelative(0, 2)
			Sleep(5)
			MoveMouseRelative(1, 2)
		if (IsLeftNotPressed()) then return end
			Sleep(86)
			MoveMouseRelative(-2, 1)
			Sleep(10)
			MoveMouseRelative(-3, 1)
			Sleep(10)
			MoveMouseRelative(-3, 2)
			Sleep(10)
			MoveMouseRelative(-3, 2)
		if (IsLeftNotPressed()) then return end
			Sleep(71)
			MoveMouseRelative(-3, 1)
			Sleep(16)
			MoveMouseRelative(-4, 1)
			Sleep(16)
			MoveMouseRelative(-4, 1)
			Sleep(16)
			MoveMouseRelative(-4, 1)
		if (IsLeftNotPressed()) then return end
			Sleep(47)
			MoveMouseRelative(-3, 1)
			Sleep(13)
			MoveMouseRelative(-3, 1)
			Sleep(13)
			MoveMouseRelative(-3, 1)
			Sleep(13)
			MoveMouseRelative(-3, 2)
		if (IsLeftNotPressed()) then return end
			Sleep(56)
			MoveMouseRelative(0, 1)
			Sleep(5)
			MoveMouseRelative(0, 1)
			Sleep(5)
			MoveMouseRelative(0, 1)
			Sleep(5)
			MoveMouseRelative(-1, 1)
		if (IsLeftNotPressed()) then return end
			Sleep(84)
			MoveMouseRelative(1, 0)
			Sleep(5)
			MoveMouseRelative(1, 1)
			Sleep(5)
			MoveMouseRelative(1, 1)
			Sleep(5)
			MoveMouseRelative(1, 1)
		if (IsLeftNotPressed()) then return end
			Sleep(85)
			MoveMouseRelative(2, 0)
			Sleep(8)
			MoveMouseRelative(2, 1)
			Sleep(8)
			MoveMouseRelative(2, 1)
			Sleep(8)
			MoveMouseRelative(2, 1)
		if (IsLeftNotPressed()) then return end
			Sleep(72)
			MoveMouseRelative(2, 0)
			Sleep(10)
			MoveMouseRelative(2, 0)
			Sleep(10)
			MoveMouseRelative(3, 1)
			Sleep(10)
			MoveMouseRelative(3, 1)
		if (IsLeftNotPressed()) then return end
			Sleep(66)
			MoveMouseRelative(2, 0)
			Sleep(10)
			MoveMouseRelative(3, 0)
			Sleep(10)
			MoveMouseRelative(3, 1)
			Sleep(10)
			MoveMouseRelative(3, 1)
		if (IsLeftNotPressed()) then return end
			Sleep(71)
			MoveMouseRelative(1, 0)
			Sleep(8)
			MoveMouseRelative(1, 1)
			Sleep(8)
			MoveMouseRelative(2, 1)
			Sleep(8)
			MoveMouseRelative(2, 1)
		if (IsLeftNotPressed()) then return end
			Sleep(72)
			MoveMouseRelative(1, 0)
			Sleep(5)
			MoveMouseRelative(1, 0)
			Sleep(5)
			MoveMouseRelative(1, 0)
			Sleep(5)
			MoveMouseRelative(1, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(81)
			MoveMouseRelative(-1, 1)
		if (IsLeftNotPressed()) then return end
			Sleep(102)
			MoveMouseRelative(-1, 0)
			Sleep(3)
			MoveMouseRelative(-1, 0)
			Sleep(3)
			MoveMouseRelative(-1, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(91)
			MoveMouseRelative(-1, 0)
			Sleep(5)
			MoveMouseRelative(-1, 0)
			Sleep(5)
			MoveMouseRelative(-1, 0)
			Sleep(5)
			MoveMouseRelative(-2, 1)
		if (IsLeftNotPressed()) then return end
			Sleep(86)
			MoveMouseRelative(-1, 0)
			Sleep(5)
			MoveMouseRelative(-2, 0)
			Sleep(5)
			MoveMouseRelative(-2, 0)
			Sleep(5)
			MoveMouseRelative(-2, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(81)
			MoveMouseRelative(-1, 0)
			Sleep(5)
			MoveMouseRelative(-2, 0)
			Sleep(5)
			MoveMouseRelative(-2, 0)
			Sleep(4)
			MoveMouseRelative(-2, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(80)
			MoveMouseRelative(-2, 0)
			Sleep(8)
			MoveMouseRelative(-2, 0)
			Sleep(8)
			MoveMouseRelative(-2, 0)
			Sleep(7)
			MoveMouseRelative(-2, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(70)
			MoveMouseRelative(-2, 0)
			Sleep(8)
			MoveMouseRelative(-2, 0)
			Sleep(8)
			MoveMouseRelative(-2, 0)
			Sleep(8)
			MoveMouseRelative(-2, 0)
			Sleep(81)
			MoveMouseRelative(-1, 0)
			Sleep(7)
			MoveMouseRelative(-2, 0)
			Sleep(8)
			MoveMouseRelative(-2, 0)
			Sleep(8)
			MoveMouseRelative(-2, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(70)
			MoveMouseRelative(-1, 0)
			Sleep(8)
			MoveMouseRelative(-2, 0)
			Sleep(8)
			MoveMouseRelative(-2, 0)
			Sleep(8)
			MoveMouseRelative(-2, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(75)
			MoveMouseRelative(-1, 0)
			Sleep(5)
			MoveMouseRelative(-1, 0)
			Sleep(5)
			MoveMouseRelative(-1, 0)
			Sleep(5)
			MoveMouseRelative(-2, -1)
		if (IsLeftNotPressed()) then return end
			Sleep(85)
			MoveMouseRelative(-1, 0)
			Sleep(5)
			MoveMouseRelative(-1, 0)
			Sleep(5)
			MoveMouseRelative(-1, 0)
			Sleep(5)
			MoveMouseRelative(-1, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(80)
			MoveMouseRelative(-1, 0)
			MoveMouseRelative(0, 0)
		until (IsLeftNotPressed())
	end


	elseif gun == MP5A4_X8_SCOPE then
		if kickback then
		repeat
		if (IsLeftNotPressed()) then return end
			MoveMouseRelative(0, 11)
			Sleep(12)
			MoveMouseRelative(0, 11)
			Sleep(13)
			MoveMouseRelative(0, 11)
			Sleep(13)
			MoveMouseRelative(0, 15)
		if (IsLeftNotPressed()) then return end
			Sleep(75)
			MoveMouseRelative(0, 15)
			Sleep(15)
			MoveMouseRelative(0, 15)
			Sleep(15)
			MoveMouseRelative(0, 15)
			Sleep(15)
			MoveMouseRelative(0, 19)
		if (IsLeftNotPressed()) then return end
			Sleep(55)
			MoveMouseRelative(0, 19)
			Sleep(18)
			MoveMouseRelative(0, 19)
			Sleep(18)
			MoveMouseRelative(0, 19)
			Sleep(18)
			MoveMouseRelative(0, 19)
		if (IsLeftNotPressed()) then return end
			Sleep(38)
			MoveMouseRelative(4, 19)
			Sleep(18)
			MoveMouseRelative(8, 19)
			Sleep(18)
			MoveMouseRelative(8, 19)
			Sleep(18)
			MoveMouseRelative(8, 19)
		if (IsLeftNotPressed()) then return end
			Sleep(47)
			MoveMouseRelative(15, 15)
			Sleep(23)
			MoveMouseRelative(15, 15)
			Sleep(23)
			MoveMouseRelative(19, 15)
			Sleep(23)
			MoveMouseRelative(19, 19)
		if (IsLeftNotPressed()) then return end
			Sleep(28)
			MoveMouseRelative(19, 11)
			Sleep(20)
			MoveMouseRelative(19, 11)
			Sleep(20)
			MoveMouseRelative(19, 15)
			Sleep(20)
			MoveMouseRelative(19, 15)
		if (IsLeftNotPressed()) then return end
			Sleep(37)
			MoveMouseRelative(11, 8)
			Sleep(16)
			MoveMouseRelative(11, 8)
			Sleep(16)
			MoveMouseRelative(11, 8)
			Sleep(16)
			MoveMouseRelative(15, 8)
		if (IsLeftNotPressed()) then return end
			Sleep(45)
			MoveMouseRelative(0, 4)
			Sleep(5)
			MoveMouseRelative(0, 4)
			Sleep(5)
			MoveMouseRelative(0, 8)
			Sleep(5)
			MoveMouseRelative(4, 8)
		if (IsLeftNotPressed()) then return end
			Sleep(86)
			MoveMouseRelative(-8, 4)
			Sleep(10)
			MoveMouseRelative(-12, 4)
			Sleep(10)
			MoveMouseRelative(-12, 8)
			Sleep(10)
			MoveMouseRelative(-12, 8)
		if (IsLeftNotPressed()) then return end
			Sleep(71)
			MoveMouseRelative(-12, 4)
			Sleep(16)
			MoveMouseRelative(-16, 4)
			Sleep(16)
			MoveMouseRelative(-16, 4)
			Sleep(16)
			MoveMouseRelative(-16, 4)
		if (IsLeftNotPressed()) then return end
			Sleep(47)
			MoveMouseRelative(-12, 4)
			Sleep(13)
			MoveMouseRelative(-12, 4)
			Sleep(13)
			MoveMouseRelative(-12, 4)
			Sleep(13)
			MoveMouseRelative(-12, 8)
		if (IsLeftNotPressed()) then return end
			Sleep(56)
			MoveMouseRelative(0, 4)
			Sleep(5)
			MoveMouseRelative(0, 4)
			Sleep(5)
			MoveMouseRelative(0, 4)
			Sleep(5)
			MoveMouseRelative(-4, 4)
		if (IsLeftNotPressed()) then return end
			Sleep(84)
			MoveMouseRelative(4, 0)
			Sleep(5)
			MoveMouseRelative(4, 4)
			Sleep(5)
			MoveMouseRelative(4, 4)
			Sleep(5)
			MoveMouseRelative(4, 4)
		if (IsLeftNotPressed()) then return end
			Sleep(85)
			MoveMouseRelative(8, 0)
			Sleep(8)
			MoveMouseRelative(8, 4)
			Sleep(8)
			MoveMouseRelative(8, 4)
			Sleep(8)
			MoveMouseRelative(8, 4)
		if (IsLeftNotPressed()) then return end
			Sleep(72)
			MoveMouseRelative(8, 0)
			Sleep(10)
			MoveMouseRelative(8, 0)
			Sleep(10)
			MoveMouseRelative(11, 4)
			Sleep(10)
			MoveMouseRelative(11, 4)
		if (IsLeftNotPressed()) then return end
			Sleep(66)
			MoveMouseRelative(8, 0)
			Sleep(10)
			MoveMouseRelative(11, 0)
			Sleep(10)
			MoveMouseRelative(11, 4)
			Sleep(10)
			MoveMouseRelative(11, 4)
		if (IsLeftNotPressed()) then return end
			Sleep(71)
			MoveMouseRelative(4, 0)
			Sleep(8)
			MoveMouseRelative(4, 4)
			Sleep(8)
			MoveMouseRelative(8, 4)
			Sleep(8)
			MoveMouseRelative(8, 4)
		if (IsLeftNotPressed()) then return end
			Sleep(72)
			MoveMouseRelative(4, 0)
			Sleep(5)
			MoveMouseRelative(4, 0)
			Sleep(5)
			MoveMouseRelative(4, 0)
			Sleep(5)
			MoveMouseRelative(4, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(81)
			MoveMouseRelative(-4, 4)
		if (IsLeftNotPressed()) then return end
			Sleep(102)
			MoveMouseRelative(-4, 0)
			Sleep(3)
			MoveMouseRelative(-4, 0)
			Sleep(3)
			MoveMouseRelative(-4, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(91)
			MoveMouseRelative(-4, 0)
			Sleep(5)
			MoveMouseRelative(-4, 0)
			Sleep(5)
			MoveMouseRelative(-4, 0)
			Sleep(5)
			MoveMouseRelative(-8, 4)
		if (IsLeftNotPressed()) then return end
			Sleep(86)
			MoveMouseRelative(-4, 0)
			Sleep(5)
			MoveMouseRelative(-8, 0)
			Sleep(5)
			MoveMouseRelative(-8, 0)
			Sleep(5)
			MoveMouseRelative(-8, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(81)
			MoveMouseRelative(-4, 0)
			Sleep(5)
			MoveMouseRelative(-8, 0)
			Sleep(5)
			MoveMouseRelative(-8, 0)
			Sleep(4)
			MoveMouseRelative(-8, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(80)
			MoveMouseRelative(-8, 0)
			Sleep(8)
			MoveMouseRelative(-8, 0)
			Sleep(8)
			MoveMouseRelative(-8, 0)
			Sleep(7)
			MoveMouseRelative(-8, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(70)
			MoveMouseRelative(-8, 0)
			Sleep(8)
			MoveMouseRelative(-8, 0)
			Sleep(8)
			MoveMouseRelative(-8, 0)
			Sleep(8)
			MoveMouseRelative(-8, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(81)
			MoveMouseRelative(-4, 0)
			Sleep(7)
			MoveMouseRelative(-8, 0)
			Sleep(8)
			MoveMouseRelative(-8, 0)
			Sleep(8)
			MoveMouseRelative(-8, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(70)
			MoveMouseRelative(-4, 0)
			Sleep(8)
			MoveMouseRelative(-8, 0)
			Sleep(8)
			MoveMouseRelative(-8, 0)
			Sleep(8)
			MoveMouseRelative(-8, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(75)
			MoveMouseRelative(-4, 0)
			Sleep(5)
			MoveMouseRelative(-4, 0)
			Sleep(5)
			MoveMouseRelative(-4, 0)
			Sleep(5)
			MoveMouseRelative(-8, -4)
		if (IsLeftNotPressed()) then return end
			Sleep(85)
			MoveMouseRelative(-4, 0)
			Sleep(5)
			MoveMouseRelative(-4, 0)
			Sleep(5)
			MoveMouseRelative(-4, 0)
			Sleep(5)
			MoveMouseRelative(-4, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(80)
			MoveMouseRelative(-4, 0)
			MoveMouseRelative(0, 0)
			MoveMouseRelative(0, 0)
		until (IsLeftNotPressed())
	end


	elseif gun == TOMPSON then
		if kickback then
		repeat
		if (IsLeftNotPressed()) then return end
			MoveMouseRelative(-4, 4)
			Sleep(14)
			MoveMouseRelative(-3, 4)
			Sleep(14)
			MoveMouseRelative(-3, 4)
			Sleep(14)
			MoveMouseRelative(-1, 3)
			Sleep(14)
			MoveMouseRelative(0, 2)
			Sleep(14)
			MoveMouseRelative(0, 1)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(0)
			Sleep(14)
		if (IsLeftNotPressed()) then return end
			MoveMouseRelative(-2, 4)
			Sleep(14)
			MoveMouseRelative(-1, 4)
			Sleep(14)
			MoveMouseRelative(-1, 4)
			Sleep(14)
			MoveMouseRelative(-1, 4)
			Sleep(14)
			MoveMouseRelative(0, 4)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(0)
			Sleep(14)
		if (IsLeftNotPressed()) then return end
			MoveMouseRelative(2, 4)
			Sleep(14)
			MoveMouseRelative(1, 4)
			Sleep(14)
			MoveMouseRelative(0, 4)
			Sleep(14)
			MoveMouseRelative(0, 4)
			Sleep(14)
			MoveMouseRelative(0, 2)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(0)
			Sleep(14)
		if (IsLeftNotPressed()) then return end
			MoveMouseRelative(2, 4)
			Sleep(14)
			MoveMouseRelative(2, 4)
			Sleep(14)
			MoveMouseRelative(2, 2)
			Sleep(14)
			MoveMouseRelative(2, 2)
			Sleep(14)
			MoveMouseRelative(0, 2)
			Sleep(14)
			MoveMouseRelative(0, 2)
			Sleep(14)
			MoveMouseRelative(0, 2)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(0)
			Sleep(14)
		if (IsLeftNotPressed()) then return end
			MoveMouseRelative(2, 4)
			Sleep(14)
			MoveMouseRelative(2, 4)
			Sleep(14)
			MoveMouseRelative(2, 4)
			Sleep(14)
			MoveMouseRelative(2, 2)
			Sleep(14)
			MoveMouseRelative(2, 1)
			Sleep(14)
			MoveMouseRelative(0, 1)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(0)
			Sleep(14)
		if (IsLeftNotPressed()) then return end
			MoveMouseRelative(2, 4)
			Sleep(14)
			MoveMouseRelative(2, 4)
			Sleep(14)
			MoveMouseRelative(2, 2)
			Sleep(14)
			MoveMouseRelative(2, 2)
			Sleep(14)
			MoveMouseRelative(0, 1)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(0)
			Sleep(14)
		if (IsLeftNotPressed()) then return end
			MoveMouseRelative(0, 2)
			Sleep(14)
			MoveMouseRelative(0, 2)
			Sleep(14)
			MoveMouseRelative(1, 2)
			Sleep(14)
			MoveMouseRelative(1, 1)
			Sleep(14)
			MoveMouseRelative(0, 1)
			Sleep(14)
			MoveMouseRelative(0, 1)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(0)
			Sleep(14)
		if (IsLeftNotPressed()) then return end
			MoveMouseRelative(-2, 4)
			Sleep(14)
			MoveMouseRelative(-2, 4)
			Sleep(14)
			MoveMouseRelative(-2, 2)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(0)
			Sleep(14)
		if (IsLeftNotPressed()) then return end
			MoveMouseRelative(-2, 4)
			Sleep(14)
			MoveMouseRelative(-2, 4)
			Sleep(14)
			MoveMouseRelative(-2, 2)
			Sleep(14)
			MoveMouseRelative(-2, 0)
			Sleep(14)
			MoveMouseRelative(-1, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(0)
			Sleep(14)
		if (IsLeftNotPressed()) then return end
			MoveMouseRelative(-2, 4)
			Sleep(14)
			MoveMouseRelative(-2, 4)
			Sleep(14)
			MoveMouseRelative(-2, 0)
			Sleep(14)
			MoveMouseRelative(-2, 0)
			Sleep(14)
			MoveMouseRelative(-2, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(0)
			Sleep(14)
		if (IsLeftNotPressed()) then return end
			MoveMouseRelative(-2, 2)
			Sleep(14)
			MoveMouseRelative(-2, 2)
			Sleep(14)
			MoveMouseRelative(-1, 2)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(0)
			Sleep(14)
		if (IsLeftNotPressed()) then return end
			MoveMouseRelative(1, 2)
			Sleep(14)
			MoveMouseRelative(1, 2)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(0)
			Sleep(14)
		if (IsLeftNotPressed()) then return end
			MoveMouseRelative(2, 2)
			Sleep(14)
			MoveMouseRelative(2, 2)
			Sleep(14)
			MoveMouseRelative(2, 2)
			Sleep(14)
			MoveMouseRelative(1, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(0)
			Sleep(14)
		if (IsLeftNotPressed()) then return end
			MoveMouseRelative(2, 2)
			Sleep(14)
			MoveMouseRelative(2, 2)
			Sleep(14)
			MoveMouseRelative(2, 2)
			Sleep(14)
			MoveMouseRelative(1, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(0)
			Sleep(14)
		if (IsLeftNotPressed()) then return end
			MoveMouseRelative(2, 2)
			Sleep(14)
			MoveMouseRelative(2, 2)
			Sleep(14)
			MoveMouseRelative(2, 0)
			Sleep(14)
			MoveMouseRelative(1, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(0)
			Sleep(14)
		if (IsLeftNotPressed()) then return end
			MoveMouseRelative(2, 2)
			Sleep(14)
			MoveMouseRelative(2, 2)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(0)
			Sleep(14)
		if (IsLeftNotPressed()) then return end
			MoveMouseRelative(-1, 2)
			Sleep(14)
			MoveMouseRelative(-1, 2)
			Sleep(14)
			MoveMouseRelative(0, 1)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(0)
			Sleep(14)
		if (IsLeftNotPressed()) then return end
			MoveMouseRelative(-2, 2)
			Sleep(14)
			MoveMouseRelative(-2, 2)
			Sleep(14)
			MoveMouseRelative(-1, 2)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(0)
			Sleep(14)
		if (IsLeftNotPressed()) then return end
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(0)
			Sleep(14)
		if (IsLeftNotPressed()) then return end
			MoveMouseRelative(-2, 1)
			Sleep(14)
			MoveMouseRelative(-2, 1)
			Sleep(14)
			MoveMouseRelative(-1, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
		if (IsLeftNotPressed()) then return end
			Sleep(0)
			Sleep(14)
		if (IsLeftNotPressed()) then return end
			MoveMouseRelative(-2, 2)
			Sleep(14)
			MoveMouseRelative(-1, 2)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
			MoveMouseRelative(0, 0)
			Sleep(14)
		until (IsLeftNotPressed())
	end
end
end